# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-07 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20171007_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eth',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eth',
            name='public',
            field=models.CharField(max_length=100),
        ),
    ]
