# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20171007_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eth',
            options={'verbose_name': 'Eth address', 'verbose_name_plural': 'Eth addresses'},
        ),
    ]
