# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20171010_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eth',
            options={'verbose_name': 'ETH адрес', 'verbose_name_plural': 'ETH адреса'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'BTC адрес', 'verbose_name_plural': 'BTC адреса'},
        ),
    ]
