# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eth',
            name='user',
        ),
        migrations.AddField(
            model_name='btc',
            name='address',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='btc',
            name='invoice',
            field=models.CharField(max_length=53, null=True),
        ),
        migrations.AddField(
            model_name='btc',
            name='redeem_code',
            field=models.CharField(max_length=53, null=True),
        ),
        migrations.DeleteModel(
            name='ETH',
        ),
    ]
