# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20171011_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='btc',
            name='address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btc',
            name='invoice',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btc',
            name='payment_code',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eth',
            name='address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eth',
            name='private',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eth',
            name='public',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
